// <auto-generated />
namespace Komis_motocykli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Zmianapolzamowien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zmianapolzamowien));
        
        string IMigrationMetadata.Id
        {
            get { return "201703302202179_Zmiana pol zamowien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
